### ISSUE TITLE
Unexpected diffs

### ISSUE THREAD

**Issue by Davorak** [myobie/htmldiff#9]
Documenting results I found to be suprising:

installed via npm, htmldiff@0.0.4

Combining tags from both before and after:
```.js
diff('<p>a <b>test</b></p>', '<p>a <div>test</div></p>')
'<p>a <b><div>test</b></div></p>'
```
Would not expect 'b' tag to remain in diff if it was not inside a <del> tag.

keeping tags
```.js
diff('<p>a <b>test</b></p>', '<p>a test</p>')
'<p>a <b>test</b></p>'
```
Would expect '<p>a <del><b>test</b></del><ins>test</ins></p>' or something similar

Remove a tag and edit text is a little better:
```.js
diff('<p>a <b>test</b></p>', '<p>a testt</p>')
'<p>a <b><del>test</del></b><ins>testt</ins></p>'
```

**Comment by myobie** [comment]
@Davorak this repo is not the npm package.
